version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /tools/codekeeper
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /packages/codekeeper
    schedule:
      interval: weekly
